version: 1.0.3.{build}
os: Previous Visual Studio 2017
platform: Any CPU
configuration: Release

branches:
  only:
    - master
skip_commits:
  message: /skip ci/      # Regex for matching commit message

skip_tags: true

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  
build_script:
  - ps: cd InstagramApiSharp 
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build -c release
  - ps: dotnet pack -c release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

artifacts:
  - path: '**\*.nupkg'

deploy:
 - provider: NuGet
   server: https://www.myget.org/F/InstagramApiSharp/api/v3
   symbol_server: https://www.myget.org/F/InstagramApiSharp/symbols/api/v3/package
   artifact: /.*\.nupkg/
   on:
     branch: master

test: off
